name: Build Android APK

on:
  workflow_dispatch: # Mengizinkan Anda menekan tombol "Build" secara manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Capacitor Dependencies
        run: npm install

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Android Project
        run: |
          npx cap add android
          npx cap sync android

      - name: Build APK (Debug Mode)
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: FinToDo-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
